### ISSUE TITLE
How to test `error` function

### ISSUE THREAD

**Issue by umihui** [fengyuanchen/compressorjs#120]
I would like to test the `error` function, how could I trigger that?
I have tried `throw new Error()` in `success`.

**Comment by tedmx** [comment]
`error` corresponds to `this.fail` calls in `index.js`, so you may want to check out invocations of `fail` there.

From what I see, there are a few trivial cases invoking `error`, like when `undefined` is supplied to `Compressor` instead of a file. 

Also seeing mappings from native `onerror` \ `onabort` events of `Image` and `FileReader`. But these may be tougher to trigger.

So, simply put, try to pass an `undefined` to `Compressor` or to upload non-image file. This should call `error` option.

**Comment by umihui** [comment]
@tedmx Thank you, it works.
