### ISSUE TITLE
Is there a way to synchronize？

### ISSUE THREAD

**Issue by Gianna-w** [fengyuanchen/compressorjs#152]

**Comment by fengyuanchen** [comment]
What does "synchronize" mean exactly?

**Comment by josuemoragl** [comment]
Hi!, I guess Giana means to in order to ingress data return the compressed data with the same order. I have the same issue, I need to compare the two images, so I get to arrays, one for the original images and the other for the compressed images. When I show the comparison, the images order in both array are different.

**Comment by fengyuanchen** [comment]
You can use `async/await` and `Promise` for that:

```js
async function compress(image) {
  return new Promise((resolve, reject) => {
    new Compressor(image, {
      success: resolve,
      error: reject,
    });
  }
}

async function process(images) {
  for (const image of images) {
    await compress(image);
  }
}

process(images);
```

**Comment by josuemoragl** [comment]
Thanks so much for your help Fengyuanchen
