### ISSUE TITLE
Is it possible to compress any sized image into a squared one?

### ISSUE THREAD

**Issue by MapleYe** [fengyuanchen/compressorjs#32]
Is there a way to change the aspect ratio of an image?

**Comment by Loktor** [comment]
I forked the lib some time ago, and implemented a feature that automatically scales the image down and crops it to the specified width/height e.q. changes the aspect ratio: https://github.com/Loktor/image-compressor maybe this does what your looking for (Option is scaleAndCenterCrop)? (haven't created a pr yet for the main lib because i am not sure if this feature fits into the core)
