### ISSUE TITLE
image is not compressed when the size is less than 800kb

### ISSUE THREAD

**Issue by alactic** [fengyuanchen/compressorjs#55]

**Comment by fengyuanchen** [comment]
Any online demo?

**Comment by an9949an** [comment]
Same issue. As I understand its depends of dimensions of image. Compression not work for small images like 200X200.

**Comment by an9949an** [comment]
You can easily reproduce it using this demo:
https://xkeshi.github.io/image-compressor/
Just try to compress some small image.
![default](https://user-images.githubusercontent.com/7009768/45840394-8652a880-bd1f-11e8-999b-0c15e8bedcb3.png)

**Comment by andipavllo** [comment]
Had the same issue, adding `minWidth / minHeight`, even `0`,  to the options fixed it.

**Comment by fengyuanchen** [comment]
Will output the original image instead of the compressed one when the size of the compressed image is greater than the original one's, except the following cases:

- The `mimeType` option is set and its value is different from the mime type of the image.
- The `width` option is set and its value is greater than the natural width of the image.
- The `height` option is set and its value is greater than the natural height of the image.
- The `minWidth` option is set and its value is greater than the natural width of the image.
- The `minHeight` option is set and its value is greater than the natural height of the image.
